module.exports = {
  apps: [
    {
      name: 'eagle-flash-web',
      script: 'node_modules/next/dist/bin/next',
      args: 'start -p 3000',
      cwd: './apps/web',
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
      },
      instances: 1,
      autorestart: true,
      max_memory_restart: '1G',
      error_file: './logs/web-error.log',
      out_file: './logs/web-out.log',
      time: true,
    },
    {
      name: 'eagle-flash-cloud-scanner',
      script: 'scripts/server_scanner.mjs',
      cwd: './',
      env: {
        NODE_ENV: 'production',
        SCAN_INTERVAL_MS: 30000,
      },
      autorestart: true,
      restart_delay: 5000,
      max_memory_restart: '500M',
      error_file: './logs/scanner-error.log',
      out_file: './logs/scanner-out.log',
      time: true,
    },
    {
      name: 'eagle-flash-tpsl-monitor',
      script: 'scripts/tpsl_monitor_worker.mjs',
      cwd: './',
      env: {
        NODE_ENV: 'production',
      },
      autorestart: true,
      restart_delay: 5000,
      max_memory_restart: '500M',
      error_file: './logs/tpsl-error.log',
      out_file: './logs/tpsl-out.log',
      time: true,
    },
    {
      name: 'eagle-flash-discord-worker',
      script: 'scripts/discord_worker.mjs',
      cwd: './',
      env: {
        NODE_ENV: 'production',
      },
      autorestart: true,
      restart_delay: 5000,
      max_memory_restart: '500M',
      error_file: './logs/discord-error.log',
      out_file: './logs/discord-out.log',
      time: true,
    },
    {
      name: 'eagle-flash-telegram-outbox-worker',
      script: 'scripts/telegram_worker.mjs',
      cwd: './',
      env: {
        NODE_ENV: 'production',
      },
      autorestart: true,
      restart_delay: 5000,
      max_memory_restart: '500M',
      error_file: './logs/telegram-outbox-error.log',
      out_file: './logs/telegram-outbox-out.log',
      time: true,
    },
    {
      name: 'eagle-flash-telegram-bot',
      script: 'scripts/telegram_poll.mjs',
      cwd: './',
      env: {
        NODE_ENV: 'production',
      },
      autorestart: true,
      restart_delay: 5000,
      max_memory_restart: '500M',
      error_file: './logs/telegram-bot-error.log',
      out_file: './logs/telegram-bot-out.log',
      time: true,
    },
    {
      name: 'eagle-flash-bigcap-worker',
      script: 'scripts/bigcap_worker.mjs',
      cwd: './',
      env: {
        NODE_ENV: 'production',
      },
      autorestart: true,
      restart_delay: 5000,
      max_memory_restart: '500M',
      error_file: './logs/bigcap-error.log',
      out_file: './logs/bigcap-out.log',
      time: true,
    },
    {
      name: 'eagle-flash-checkpoint-worker',
      script: 'scripts/checkpoint_evaluator.mjs',
      args: '--loop',
      cwd: './',
      env: {
        NODE_ENV: 'production',
        EVAL_INTERVAL_MS: 60000,
      },
      autorestart: true,
      restart_delay: 5000,
      max_memory_restart: '500M',
      error_file: './logs/checkpoint-error.log',
      out_file: './logs/checkpoint-out.log',
      time: true,
    },
    {
      name: 'eagle-flash-whale-detector',
      script: 'scripts/whale_detector_worker.mjs',
      cwd: './',
      env: {
        NODE_ENV: 'production',
      },
      autorestart: true,
      restart_delay: 5000,
      max_memory_restart: '500M',
      error_file: './logs/whale-detector-error.log',
      out_file: './logs/whale-detector-out.log',
      time: true,
    },
    {
      name: 'eagle-flash-etherscan-scanner',
      script: 'scripts/etherscan_whale_worker.mjs',
      cwd: './',
      env: {
        NODE_ENV: 'production',
      },
      autorestart: true,
      restart_delay: 5000,
      max_memory_restart: '500M',
      error_file: './logs/etherscan-error.log',
      out_file: './logs/etherscan-out.log',
      time: true,
    },
    {
      name: 'eagle-flash-listing-worker',
      script: 'scripts/new_listing_worker.mjs',
      cwd: './',
      env: {
        NODE_ENV: 'production',
        POLL_INTERVAL_MS: 45000,
      },
      autorestart: true,
      restart_delay: 5000,
      max_memory_restart: '500M',
      error_file: './logs/listing-worker-error.log',
      out_file: './logs/listing-worker-out.log',
      time: true,
    },
    {
      name: 'eagle-flash-performance-worker',
      script: 'scripts/performance_worker.mjs',
      cwd: './',
      env: {
        NODE_ENV: 'production',
      },
      autorestart: true,
      restart_delay: 5000,
      max_memory_restart: '500M',
      error_file: './logs/performance-worker-error.log',
      out_file: './logs/performance-worker-out.log',
      time: true,
    },
  ],
};

